import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import SmoothScroll from "@/components/dom/layout/SmoothScroll";
import MagneticCursor from "@/components/dom/ui/MagneticCursor";
import Header from "@/components/dom/layout/Header";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased custom-cursor`}
      >
        <SmoothScroll>
          {/* Global Cursor */}
          <MagneticCursor />
          <Header />
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
